### ISSUE TITLE
Bug in IPV4 header checksum calculation

### ISSUE THREAD

**Issue by bkuker** [ardikars/pcap#149]
If you have an entire Ethernet packet, and you use the codec features like this:
```
Ethernet ethernet = buffer.cast(Ethernet.class);
Ip4 ip4 = buffer.readerIndex(ethernet.size()).cast(Ip4.class);
ip4.checksum(ip4.calculateChecksum());
```

The wrong checksum is calculated. That is because the `accumulation -= buffer.getShort(10) & 0xFFFF;` in Ip4::calculateChecksum is trying to remove the preexisting checksum from checksum calculation (which is the correct thing to do) but the address of the checksum it is trying to remove, `10`, is only correct when the Ip4 was constructed with offset zero.

If the Ip4 header is part of a larger buffer, in my case an Ethernet packet, then it is grabbing some arbitrary bytes from the middle of the MAC address in the ethernet header.

```
  public int calculateChecksum() {
    int accumulation = Checksum.sum(buffer, offset, ihl() << 2);
    accumulation -= buffer.getShort(10) & 0xFFFF;
    accumulation = (accumulation >> 16 & 0xFFFF) + (accumulation & 0xFFFF);
    return (~accumulation & 0xFFFF);
  }
```

The correct code would be
```
accumulation -= buffer.getShort(headerChecksum) & 0xFFFF;
```

**Comment by ardikars** [comment]
Thanks for reporting this issue. It should be [fixed](https://github.com/ardikars/pcap/pull/150) on version 1.3.2.
