### ISSUE TITLE
The library doesn't support Filter having spaces

### ISSUE THREAD

**Issue by naveengauba** [ardikars/pcap#64]
Hi.. I am trying to write a packet capture which captures http traffic. This is how my program looks like.

`DefaultLiveOptions liveOptions = new DefaultLiveOptions();
	liveOptions.promiscuous(false).timeout(readTimeoutMillis).bufferSize(bufferSize)
								.snapshotLength(snapLength);
						StringBuilder sbBpfFilter = new StringBuilder("tcp port ").append(80).append(" or ").append(443).append(" and dst ").append(defaultInterfaceAddress.getHostAddress());
						String bpfFilter = sbBpfFilter.toString();
						pcapHandle = pcapService.live(pcapNetworkInterface, liveOptions);
						pcapHandle.setNonBlock(true);
						pcapHandle.setFilter(bpfFilter, true);
						// Start capturing packets in an infinite loop
						pcapHandle.loop(-1, new MyPacketHandler(pcapHandle), "Hello pcap!");
`

The program throws exception saying the filter is empty. But if you look at the logger its not empty. It does have spaces.
`23:43:51.818 [PacketSnifferThread] INFO  c.q.k.h.p.PerformancePacketSniffer - BPF filter:tcp port 9090 or 9443 and dst 192.168.4.27
pcap_can_set_frmon: Function doesn't exist.
pcap_can_set_rfmon: pcap_statustostr: Function doesn't exist.
23:43:51.836 [PacketSnifferThread] ERROR c.q.k.h.p.PerformancePacketSniffer - Exception starting packet capture
java.lang.IllegalArgumentException: filter: null (expected: filter != null && notBlank(filter))
	at pcap.jdk7.internal.DefaultPcap.setFilter(DefaultPcap.java:74) ~[pcap-jdk7-0.8.3.jar:na]
	at com.qumu.kodiak.http.perf.PerformancePacketSniffer$PacketSnifferRunnable.run(PerformancePacketSniffer.java:154) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]`
Please help.

**Comment by ardikars** [comment]
Sorry for slow response. Pease provide below details:

1. OS version
2. Java version

Thanks

**Comment by ardikars** [comment]
Thanks for reporting this issue. Fixed on version 1.0.0-alpha.2.
Tested with below code.

```
StringBuilder sbBpfFilter =
    new StringBuilder("tcp port ")
      .append(80)
      .append(" or ")
      .append(443)
      .append(" and dst ")
      .append("192.168.1.1");
DefaultLiveOptions options = new DefaultOptions()
  .proxy(PcapProxy.class); // for non-blocking (experimental)

String bpfFilter = sbBpfFilter.toString();
try (Pcap live = service.live(devices, new DefaultLiveOptions())) {
  live.setNonBlock(true); 
  live.setFilter(bpfFilter, true);
}
```
```
// Experimental feature
interface PcapProxy extends Pcap {

  @Async(timeout = 5000) // 5 seconds (using poll/WaitForSingleObject)
  @Override
  void nextEx(PacketHeader packetHeader, PacketBuffer packetBuffer)
      throws BreakException, ErrorException, TimeoutException;

  @Async(timeout = 5000)  // 5 seconds (using poll/WaitForSingleObject)
  @Override
  <T> void dispatch(int i, PacketHandler<T> packetHandler, T args)
      throws BreakException, ErrorException, TimeoutException;
}
```

**Comment by naveengauba** [comment]
Thanks so much for fixing the issue. I am testing the same on my end. Will get back I see any issues. I will be testing the packet sniffing on Mac as well as CentOS.

**Comment by naveengauba** [comment]
I was able to test the fix on MacOS and CentOS and it worked well. Thanks again. I had a requirement to parse various headers (Ethernet/IP/Tcp) from the captured Packet. Wondering if you have any plans to implement that in future.

**Comment by ardikars** [comment]
Have a look at https://github.com/ardikars/pcap/blob/development/tests/src/test/java/pcap/tests/Application.java

Thanks for using my works. For TCP stream (reassembly) I'm not sure to implement that.

*Update*
Since the pcap-codec module is incubating, better you copy-paste the packages inside that module into your own project.
